Fix(MyWallet): Review my wallet page and fix UI issues.
Viabl-Ventures/haveno-ui pull request #25
Opened 2022-05-31 21:17 UTC by abouolia

- [FIXED] nothing happens on clicking the "Download QR" button.
- [FIXED] The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
- [FIXED] QR popup style.
- [FIXED] Copy and QR text buttons
- [FIXED] "Avaliable" Balance typo.
- [FIXED] "Reservered" Funds

2022-06-01 20:24 UTC, schowdhuri requested changes
Thanks! The UI looks really good now! Minor code style comments added.

2022-06-01 20:24 UTC, schowdhuri commented on packages/main/src/services/haveno.ts
> +// @ts-ignore
Can this be fixed without suppressing eslint?

2022-06-01 20:24 UTC, schowdhuri commented on packages/main/src/services/haveno.ts
> +      function (err: Error) {
Arrow function, please

2022-06-01 20:24 UTC, schowdhuri commented on packages/main/src/services/haveno.ts
> +      file?.filePath,
Don't need the `?` here

2022-06-01 20:24 UTC, schowdhuri commented on packages/main/src/services/haveno.ts
> +      return 0;
`return` should suffice

2022-06-01 20:24 UTC, schowdhuri commented on packages/main/src/types/ipc.ts
> +
Newline not required

2022-06-01 20:24 UTC, schowdhuri commented on packages/renderer/src/components/atoms/Tabs/Tabs.tsx
> +        borderBottomColor: theme.colors.blue[6],
Nice catch :)

2022-06-01 20:24 UTC, schowdhuri commented on packages/renderer/src/components/atoms/Tabs/Tabs.tsx
> +      "&:first-of-type": {
Nice, thanks!

2022-06-01 20:24 UTC, schowdhuri commented on packages/main/src/services/haveno.ts
> +    const file = await dialog.showSaveDialog({
Good one!

2022-06-01 20:24 UTC, schowdhuri commented on packages/renderer/src/components/atoms/Typography/Anchor.tsx
> +export function Anchor(props: MAnchorProps<"a">) {
Good one!

2022-06-01 20:24 UTC, schowdhuri commented on packages/renderer/src/components/molecules/AddressCard/AddressCard.tsx
>  import { DetailItemCard } from "@atoms/DetailItemCard/DetailItemCard";
`import { DetailItemCard } from @atoms/DetailItemCard`

2022-06-02 04:30 UTC, abouolia commented on packages/main/src/services/haveno.ts
> +// @ts-ignore
I'm sorry man, I was planning to write to you and explain why i did that, :(, my bad, `qrcode` has two different libraries one for `browser` and another for `server` when i try to import the package in `main` the project try to import it as `browser` package not as `server` package, tried to search about the issue but all solutions say just change your webpack env configuration to `node`, didn't want to modify anything in webpack config. in that PR, so let it that issue to different PR.

2022-06-02 04:48 UTC, abouolia commented on packages/main/src/services/haveno.ts
> +      file?.filePath,
NO 😄

2022-06-02 15:50 UTC, schowdhuri approved these changes
Let's ship it! 🚀

2022-06-02 15:50 UTC, schowdhuri commented on packages/main/src/services/haveno.ts
> +// @ts-ignore
Gotcha. Let's roll with it for now

2022-06-02 15:50 UTC, schowdhuri commented on package.json
> +    "qrcode": "^1.5.0",
Ina future iteration I'd like to remove one of the QR libraries. Doesn't make sense to be using two

2022-06-02 16:10 UTC, merged